// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrabajoFinalProem_GalanFlorencia.datos;

#nullable disable

namespace TrabajoFinalProem_GalanFlorencia.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220504204843_MigracionInicial")]
    partial class MigracionInicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("TrabajoFinalProem_GalanFlorencia.Models.Cliente", b =>
                {
                    b.Property<int>("codigo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("codigo"), 1L, 1);

                    b.Property<int?>("Facturanumero")
                        .HasColumnType("int");

                    b.Property<string>("direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("extraSaldo")
                        .HasColumnType("real");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("codigo");

                    b.HasIndex("Facturanumero");

                    b.ToTable("Cliente");
                });

            modelBuilder.Entity("TrabajoFinalProem_GalanFlorencia.Models.Factura", b =>
                {
                    b.Property<int>("numero")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("numero"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.HasKey("numero");

                    b.ToTable("Factura");
                });

            modelBuilder.Entity("TrabajoFinalProem_GalanFlorencia.Models.Pagos", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"), 1L, 1);

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("IDCliente")
                        .HasColumnType("int");

                    b.Property<float>("importe")
                        .HasColumnType("real");

                    b.HasKey("id");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("TrabajoFinalProem_GalanFlorencia.Models.Cliente", b =>
                {
                    b.HasOne("TrabajoFinalProem_GalanFlorencia.Models.Factura", null)
                        .WithMany("Items")
                        .HasForeignKey("Facturanumero");
                });

            modelBuilder.Entity("TrabajoFinalProem_GalanFlorencia.Models.Factura", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
